### ISSUE TITLE
name.WARNING: Header x-amz-date not found, aborting request verification.

### ISSUE THREAD

**Issue by nuclearpistachio** [amzn/amazon-instant-access-sdk-php#3]
Hi there,

I'm receiving this error on the below error on the redirect test (on staging). Any ideas why this header might not be present?
name.WARNING: Header x-amz-date not found, aborting request verification.

**Comment by hz-chen** [comment]
Hi nuclearpistachio,

Sorry for the super late response, our team does not track github issues officially,
If you need further assistant, please email d3-support@amazon.com.

Thanks
